<!doctype html>
<html lang="en" ng-app="main">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>php-spa</title>

        <script src="/js/lib/jquery.js"></script>
        <script src="/js/lib/bootstrap.js"></script>
        <script src="/js/lib/angular.js"></script>
        <script src="/js/app/main.js"></script>

        <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/main.css" rel="stylesheet" media="screen">
    </head>
    <body>
    </body>
</html>
