<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>php-spa</title>

        <? foreach ($this->_meta as $property => $content): ?>
            <meta name="<?= $property; ?>"
                  property="<?= $property; ?>"
                  content="<?= $content; ?>" />
        <? endforeach; ?>
    </head>
    <body>
        php-spa was successfully installed
    </body>
</html>
